version: "3.6"
services:
  postgres:
    build: "./cmd/server/database"
    restart: "always"
    environment:
      POSTGRES_DB: "file_storage"
      POSTGRES_USER: "kulakov"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "3333:5432"