version: "3.6"
services:
  postgres:
    env_file: 
      - config.env
    build: "./"
    restart: "always"
    environment:
      POSTGRES_DB: $POSTGRES_NAME
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports: 
      - "${ADDRESS_FOR_DB}:${POSTGRES_PORT}"